### ISSUE TITLE
assetlibrary: search with colon character using HTTP integration fails

### ISSUE THREAD

**Issue by aaronatbissell** [aws/aws-connected-device-framework#49]
**Aws Connected Device Framework Affected Module(s):**
 
assetlibrary

**I'm submitting a ...**

- [x] bug report
- [ ] feature request

**Description:**

I think API gateway is decoding the query string parameters before they make their way into the assetlibrary Lambda handler function. Then the lambda handler is expecting that the query string parameters are URL encoded, but they aren't

**Current behavior:**

When trying to search for groups/devices in assetlibrary using the `contains`, `endsWith` or `startsWith` filters (although it may not be only limited to those), if the thing I am searching for has a colon `:` character, the search fails.

**Expected behavior:**

Search should treat the `:` character as a part of the search term and should return results. 

**Steps to reproduce:**

Create a group or device that has an attribute with a `:` character in it. Then try to search for that attribute using postman or invoke using HTTP client.

**Additional Information:**

Search in POSTMAN using:
{{assetlibrary_base_url}}//search?type=device&contains=macAddress:F1%3AFC

Yields this in the assetlibrary lambda logs (note, URL-decoded params)
> search.controller search: in: types:device, ancestorPath:undefined, eqs:undefined, neqs:undefined, lts:undefined, ltes:undefined, gts:undefined, gtes:undefined, startsWiths:undefined, endsWiths:undefined, **_containses:macAddress:F1:FC_**, exists:undefined, nexists:undefined, facetField:undefined, summarize:undefined, offset:undefined, count:undefined, sort:undefined

Searching using the lambda looks good
```ts
const req = new SearchRequestModel();
req.types = ["device"];
req.contains = [
{
  field: "macAddress",
  value: "F1:FC",
},
];
```
Yields this in assetlibrary lambda logs (note URL-encoded params)
> search.controller search: in:  types:device, ancestorPath:undefined, eqs:undefined, neqs:undefined,  lts:undefined, ltes:undefined, gts:undefined, gtes:undefined,  startsWiths:undefined, endsWiths:undefined,  **_containses:macAddress:F1%3AFC_**, exists:undefined, nexists:undefined,  facetField:undefined, summarize:undefined, offset:undefined,  count:undefined, sort:undefined

**Comment by jonasneu-aws** [comment]
Hi @aaronatbissell, this is indeed an annoying edge case of the search API. The example query you show above is missing one URL-encoding step. However, the documentation doesn't make that clear and it works fine without this step unless you have search values with a colon.

The safe way to format `/search` parameters is to URL-encode the search value first, then assemble the complete HTTP request parameter value (consisting of search key and search value), and finally URL-encode the whole thing again. The previous sentence expressed in pseudo-code:

```
"/search?" + queryType + "=" + urlencode( searchKey + ":" urlencode( searchValue ) )
```

Your example request would turn into:

```
{{assetlibrary_base_url}}//search?type=device&contains=macAddress%3AF1%253AFC
```

Note that when using traversals instead of simple fields as search key the colons in the search key are URL-encoded once and any colons in the search value are URL-encoded twice. In the following example, the query type is `startsWith`, the search key is `traversal:out:fieldname`, and the search value is `abc:123`:

```
{{assetlibrary_base_url}}//search?type=device&startsWith=traversal%3Aout%3Afieldname%3Aabc%253A123
```

Please let me know if that unblocks you. I will look for how to best cover this in the documentation.

**Comment by aaronatbissell** [comment]
Thanks for the explanation @jonasneu-aws! This is really helpful. So you almost need to "double encode" the search value when it includes a colon character. Is this the only character this applies to? And does the asset library client automatically account for this?

**Comment by jonasneu-aws** [comment]
> Is this the only character this applies to?

I can't think of any other characters that should cause similar problems, but that doesn't mean they don't exist. The safe and most future-proof way to handle this is to URL-encode the strings as described above and not just specific characters.

> And does the asset library client automatically account for this?

Yes. The code that does the "double encoding" is here: https://github.com/aws/aws-connected-device-framework/blob/d868cb9/source/packages/libraries/clients/assetlibrary-client/src/client/search.model.ts#L89-L90 The `encodeKey` argument you see in those lines is used whenever a HTTP request is constructed. The code paths where `encodeKey` is `false` are those where API Gateway is bypassed and the Lambda is called directly.

**Comment by aaronatbissell** [comment]
Thanks so much!
